"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ACTIONS = exports.DEFAULT_SETTINGS = exports.INTEGER_SETTINGS = exports.REGENERATE_INTERVAL_IN_MILLISECONDS = exports.MAX_TIMES_TO_TRY_TO_CREATE_NEW_GROUP = exports.LATEST_GROUPS_AMOUNT = exports.SETTING_UTC_OFFSET = exports.SETTING_REGENERATE = exports.SETTING_USERS_TO_IGNORE = exports.SETTING_LANGUAGE = exports.SETTING_DAY_TO_REGENERATE = exports.SETTING_BUDDY_GROUP_SIZE = exports.SETTING_ACTIVITIES_SUGGESTION_AMOUNT = void 0;
exports.SETTING_ACTIVITIES_SUGGESTION_AMOUNT = "SETTING_ACTIVITIES_SUGGESTION_AMOUNT";
exports.SETTING_BUDDY_GROUP_SIZE = "SETTING_BUDDY_GROUP_SIZE";
exports.SETTING_DAY_TO_REGENERATE = "SETTING_DAY_TO_REGENERATE";
exports.SETTING_LANGUAGE = "SETTING_LANGUAGE";
exports.SETTING_USERS_TO_IGNORE = "SETTING_USERS_TO_IGNORE";
exports.SETTING_REGENERATE = "SETTING_REGENERATE";
exports.SETTING_UTC_OFFSET = "SETTING_UTC_OFFSET";
exports.LATEST_GROUPS_AMOUNT = 5;
exports.MAX_TIMES_TO_TRY_TO_CREATE_NEW_GROUP = 20;
exports.REGENERATE_INTERVAL_IN_MILLISECONDS = 604800000;
exports.INTEGER_SETTINGS = [
    exports.SETTING_ACTIVITIES_SUGGESTION_AMOUNT,
    exports.SETTING_BUDDY_GROUP_SIZE,
    exports.SETTING_DAY_TO_REGENERATE,
    exports.SETTING_UTC_OFFSET,
];
exports.DEFAULT_SETTINGS = {
    SETTING_ACTIVITIES_SUGGESTION_AMOUNT: 3,
    SETTING_BUDDY_GROUP_SIZE: 2,
    SETTING_DAY_TO_REGENERATE: 1,
    SETTING_LANGUAGE: "en",
    SETTING_USERS_TO_IGNORE: "",
    SETTING_UTC_OFFSET: 1,
};
exports.ACTIONS = [
    exports.SETTING_ACTIVITIES_SUGGESTION_AMOUNT,
    exports.SETTING_BUDDY_GROUP_SIZE,
    exports.SETTING_DAY_TO_REGENERATE,
    exports.SETTING_LANGUAGE,
    exports.SETTING_REGENERATE,
    exports.SETTING_USERS_TO_IGNORE,
    exports.SETTING_UTC_OFFSET,
];
