export const SETTING_ACTIVITIES_SUGGESTION_AMOUNT =
  "SETTING_ACTIVITIES_SUGGESTION_AMOUNT";
export const SETTING_BUDDY_GROUP_SIZE = "SETTING_BUDDY_GROUP_SIZE";
export const SETTING_DAY_TO_REGENERATE = "SETTING_DAY_TO_REGENERATE";
export const SETTING_LANGUAGE = "SETTING_LANGUAGE";
export const SETTING_USERS_TO_IGNORE = "SETTING_USERS_TO_IGNORE";
export const SETTING_REGENERATE = "SETTING_REGENERATE";
export const SETTING_UTC_OFFSET = "SETTING_UTC_OFFSET";

export const LATEST_GROUPS_AMOUNT = 5;
export const MAX_TIMES_TO_TRY_TO_CREATE_NEW_GROUP = 20;
export const REGENERATE_INTERVAL_IN_MILLISECONDS = 604800000;

export const INTEGER_SETTINGS = [
  SETTING_ACTIVITIES_SUGGESTION_AMOUNT,
  SETTING_BUDDY_GROUP_SIZE,
  SETTING_DAY_TO_REGENERATE,
  SETTING_UTC_OFFSET,
];

export const DEFAULT_SETTINGS = {
  SETTING_ACTIVITIES_SUGGESTION_AMOUNT: 3,
  SETTING_BUDDY_GROUP_SIZE: 2,
  SETTING_DAY_TO_REGENERATE: 1,
  SETTING_LANGUAGE: "en",
  SETTING_USERS_TO_IGNORE: "",
  SETTING_UTC_OFFSET: 1,
};

export const ACTIONS = [
  SETTING_ACTIVITIES_SUGGESTION_AMOUNT,
  SETTING_BUDDY_GROUP_SIZE,
  SETTING_DAY_TO_REGENERATE,
  SETTING_LANGUAGE,
  SETTING_REGENERATE,
  SETTING_USERS_TO_IGNORE,
  SETTING_UTC_OFFSET,
];