export type TranslateKey =
  | 'ACTIVITIES_INTRO'
  | 'ACTIVITIES'
  | 'CREATE_BUDDIES_SETTINGS'
  | 'CURRENT_GROUPS_ARE'
  | 'GENERAL_SETTINGS_TITLE'
  | 'GREETINGS'
  | 'HOME_INTRO'
  | 'NO_GROUPS'
  | 'NOT_IN_GROUP'
  | 'QUESTION_INTRO'
  | 'QUESTIONS'
  | 'REGROUP_BUDDIES_TITLE'
  | 'REGROUP_BUTTON_LABEL'
  | 'SETTING_ACTIVITIES_SUGGESTION_AMOUNT_DESCRIPTION'
  | 'SETTING_ACTIVITIES_SUGGESTION_AMOUNT_TITLE'
  | 'SETTING_BUDDY_GROUP_SIZE_DESCRIPTION'
  | 'SETTING_BUDDY_GROUP_SIZE_TITLE'
  | 'SETTING_DAY_TO_REGENERATE_DESCRIPTION'
  | 'SETTING_DAY_TO_REGENERATE_TITLE'
  | 'SETTING_LANGUAGE_DESCRIPTION'
  | 'SETTING_LANGUAGE_TITLE'
  | 'SETTING_USERS_TO_IGNORE_DESCRIPTION'
  | 'SETTING_USERS_TO_IGNORE_TITLE'
  | 'SETTING_UTC_OFFSET_DESCRIPTION'
  | 'SETTING_UTC_OFFSET_TITLE'
  | 'SOMETHING_WENT_WRONG'
  | 'UNKNOWN_COMMAND'
  | 'WEEK'
  | 'YOU_ARE_BUDDIES_FOR'
  | 'YOU_CAN_CHAT_WITH_THEM_HERE'
  | 'YOUR_ARE_BUDDIES_WITH';

export type TranslateContent = {
  [key in TranslateKey]:
    | string
    | Array<string>
    | Array<{
        type: 'section';
        text: {
          type: string;
          text: string;
        };
      }>;
};

export type Settings = {
  SETTING_ACTIVITIES_SUGGESTION_AMOUNT?: number;
  SETTING_BUDDY_GROUP_SIZE?: number;
  SETTING_DAY_TO_REGENERATE?: number;
  SETTING_LANGUAGE?: 'en';
  SETTING_USERS_TO_IGNORE?: string;
  SETTING_UTC_OFFSET?: number;
};
